### ISSUE TITLE
Please add the feature: sliding caching

### ISSUE THREAD

**Issue by izturn** [phuslu/lru#1]
Thanks for share the nice repo, I have just added the `Loader` to my code, the new version makes it outdated ;-), the last feature I'm missing is sliding caching,  now the cache is absolute TTL, shall we add it?

**Comment by phuslu** [comment]
I think adding "sliding caching"  will not hit performance. but seems it requires to add extra 4/8 bytes (int32/int64) to record `time.Duration`, it will hit the memory efficient. Let me consider...

Maybe we could considering to decrease the TTL accuracy to seconds level (uint32), then adding the sliding will also requires another uint32(even uint16).

**Comment by phuslu** [comment]
Another option it, just fork/copy this LRU codes to your project then modify easily -- That's is the initial motivation of this library. 😄

**Comment by izturn** [comment]
so, which option is you prefer?

**Comment by phuslu** [comment]
let me try option 1, hopefully nobody won't unhappy with the TTL accuracy decreasing.

**Comment by phuslu** [comment]
I added sliding cache support in https://github.com/phuslu/lru/commit/a2799069e6b79942bd94610b180e85b8db2af059 by introduce a method `*Cache.SlidingGet(key)`, please help check
1. hope this implementation is correct, without any misunderstandings.
2. could please give advice/suggestion about the method naming? "SildingGet" seems not good enough.
3. I'm still considering do accuracy decreasing by ttl/expires from int64 -> int32

**Comment by izturn** [comment]
> I added sliding cache support in master branch by introduce a method `*Cache.SlidingGet(key)`, please help check
> 
>     1. hope this implementation is correct, without any misunderstandings.
> 
>     2. could please give advice/suggestion about the method naming? "SildingGet" seems not good enough.
> 
>     3. I'm still considering do accuracy decreasing by ttl/expires from int64 -> int32

1. nice 
2. i asked the `bard`, it seems that the all cache implemention's `Get` will be sliding, maybe `touchGet`?
3. i think accuracy decreasing is ok

**Comment by phuslu** [comment]
1. Thanks.
2. I rename to `TouchGet` and add a new method `TouchGetOrLoad`
3. I decreased the time accuracy on master branch.

**Comment by izturn** [comment]
i think we can delay/match  the `Range` to [spec: add range over int, range over func](https://github.com/golang/go/issues/61405).
btw, how about a `clear`?

**Comment by phuslu** [comment]
I reverted Range method.

And for clear, I afraid that it will introduce data race or user misunderstood/misuse, so I have no good idea to add/implement it.

**Comment by phuslu** [comment]
Please allow me close this issue.

Welcome to raise new issues for feature request/ideas, thanks again!
