### ISSUE TITLE
can u do a version which i think can be faster if you disregard the time expiry? meaning no time expiry

### ISSUE THREAD

**Issue by ouvaa** [phuslu/lru#6]
can u do a version which i think can be faster if you disregard the time expiry? meaning no time expiry

this is for maximum lru speed. i dont need the expiry field.

**Comment by phuslu** [comment]
I'm not sure how much of a speedup this will bring, but let me implement it in another branch and test it out.

**Comment by ouvaa** [comment]
@phuslu i'm sure you can come up with better. thx in advance

**Comment by phuslu** [comment]
the nossl LRU version is available here
```bash
go get -v github.com/phuslu/lru@$(git ls-remote https://github.com/phuslu/lru nottl | cut -b-40)
```

And the benchmark result is here
https://github.com/phuslu/lru/actions/runs/8308974059/job/22739812511

Considering the improvement is not too big (+13% throughputs, -20% memory usage), I'd like to keep this implementation just in the "nottl" branch.

Make sense?

**Comment by ouvaa** [comment]
are you joking?! the performance is fantastic. -20% mem usage! 13% throughputs!
i wonder why cant you just implement as both like NewWithTTL and New (the default without ttl version)

you can do this. where can i buy you coffee?

**Comment by ouvaa** [comment]
@phuslu one last thing, can you do []byte for entries keys and values instead of just string?
[]byte should be comparable too, not just strings. pls make this "native" and it'll be perfect.

**Comment by phuslu** [comment]
You convinced me. I just renamed the `New` function of the master branch to `NewTTLCache`. Then, I will introduce the code of the nottl branch.

**Comment by phuslu** [comment]
the first mixed version(LRUCache & TTLCache) is available in latest master branch.

**Comment by phuslu** [comment]
> can you do []byte for entries keys and values instead of just string

Not sure, please me give a try.
