### ISSUE TITLE
there are breaking changes, i'm using this for production now. please update the usage doc. it's getting better. thx

### ISSUE THREAD

**Issue by ouvaa** [phuslu/lru#9]
as titled

**Comment by phuslu** [comment]
I'm not clear about the "usage doc" meaning, because I think the latest README.md and example_test.go and https://pkg.go.dev/github.com/phuslu/lru already align to v1.0.10

**Comment by phuslu** [comment]
Oh, you mean if any break changes in future.  Yes, I will do update if there is.
